# 站点基础设置
remote_theme: daattali/beautiful-jekyll
title: WangRuoxi的个人网站
description: 我的项目和作品集展示
author: Wang Ruoxi

# 导航链接 - 如果你想简化顶部导航，可以减少这里的项目或完全移除
navbar-links:
  主页: "/"
  关于我: "/about"
  项目展示: "/projects"
  联系方式: "/contact"



# 移除这部分如果你不需要顶部导航栏
# 如果想完全没有导航栏，使用: navbar-links: {}

# 社交网络链接，取消注释你需要的部分
social-network-links:
  email: e1373313@u.nus.edu
  WeChat: Wrxxlsq11150901
  # github: yourusername
  # twitter: yourusername
  # patreon: yourname
  # youtube: yourchannelname
  # reddit: yourname
  linkedin: http://linkedin.com/in/ruoxi-wang-256a55325
  # xing: yourname
  # stackoverflow: "yourno/yourname"
  # instagram: yourname
  # spotify: yourname
  telephone: +86 18082936005
  # steam: yourname
  # twitch: yourname
  # yelp: yourname
  # calendly: yourname
  # mastodon: instance.url/@username

# 页面底部信息
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  github: false
  linkedin: True
  xing: false
  stackoverflow: false
  instagram: false
  telephone: true

# 网站外观设置
# 如果你不想要顶部大图，设置为false
header-img: true
# 导航栏背景色：飞燕草蓝
navbar-col: "#0F59A4"

# 导航栏文字色：白色，保证在蓝色背景上有足够对比度
navbar-text-col: "#FFFFFF"

# 导航栏边框色：使用栀子色做点缀
navbar-border-col: "#FDDB76"

# 页面背景色：略带暖意的近白色
page-col: "#FDFCF9"

# 正文字体颜色：深灰，阅读舒适
text-col: "#333333"

# 链接颜色：呼应导航栏背景的飞燕草蓝
link-col: "#0F59A4"

# 鼠标悬停颜色：使用栀子色，形成视觉跳跃
hover-col: "#FDDB76"

# 页脚背景色：与导航栏统一，使用飞燕草蓝
footer-col: "#0F59A4"

# 页脚文字颜色：同导航栏文字色
footer-text-col: "#FFFFFF"

# 页脚链接颜色：与鼠标悬停保持一致，用栀子色突出链接
footer-link-col: "#FDDB76"




# 分析和评论设置 - 不需要可以忽略
# google_analytics: ""
# disqus: ""

# 其他设置
permalink: /:year-:month-:day-:title/
paginate: 5
excerpt_length: 50
title-separator: "-"

# 高级设置
plugins:
  - jekyll-paginate
  - jekyll-sitemap


# 默认值配置
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      comments: false
