# 站点基础设置
remote_theme: daattali/beautiful-jekyll
title: WangRuoxi的个人网站
description: 我的项目和作品集展示
author: Wang Ruoxi

# 导航链接 - 如果你想简化顶部导航，可以减少这里的项目或完全移除
navbar-links: {}

# 移除这部分如果你不需要顶部导航栏
# 如果想完全没有导航栏，使用: navbar-links: {}

# 社交网络链接，取消注释你需要的部分
social-network-links:
  email: e1373313@u.nus.edu
  WeChat: Wrxxlsq11150901
  # github: yourusername
  # twitter: yourusername
  # patreon: yourname
  # youtube: yourchannelname
  # reddit: yourname
  linkedin: http://linkedin.com/in/ruoxi-wang-256a55325
  # xing: yourname
  # stackoverflow: "yourno/yourname"
  # instagram: yourname
  # spotify: yourname
  telephone: +86 18082936005/+65 83607237
  # steam: yourname
  # twitch: yourname
  # yelp: yourname
  # calendly: yourname
  # mastodon: instance.url/@username

# 页面底部信息
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  github: false
  linkedin: True
  xing: false
  stackoverflow: false
  instagram: false
  telephone: true

# 网站外观设置
# 如果你不想要顶部大图，设置为false
header-img: true
navbar-col: "#BADC58"
navbar-text-col: "#333333"
navbar-border-col: "#C7EDA0"
page-col: "#FFFFFF"
text-col: "#2F3542"
link-col: "#6AB04C"
hover-col: "#4CD137"
footer-col: "#F1F9E4"
footer-text-col: "#2F3542"
footer-link-col: "#6AB04C"

# 分析和评论设置 - 不需要可以忽略
# google_analytics: ""
# disqus: ""

# 其他设置
permalink: /:year-:month-:day-:title/
paginate: 5
excerpt_length: 50
title-separator: "-"

# 高级设置
plugins:
  - jekyll-paginate
  - jekyll-sitemap


# 默认值配置
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      comments: false
